package com.medicall.domain;

public enum CallIntent {
    HOURS, HOLIDAY, ACCESS, BELONGINGS, FAQ,
    APPOINTMENT_NEW, APPOINTMENT_CHANGE, APPOINTMENT_CANCEL,
    LAB, BILLING, PHARMACY, REFERRAL,
    IDENTITY_VERIFY, COMPLAINT, MEDICAL_QUESTION,
    EMERGENCY, HUMAN_TRANSFER, UNKNOWN
}
