spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}

server:
  port: ${SERVER_PORT:8081}

medicall:
  security:
    dev-mode: ${DEV_MODE:true}
